name: Feature Request
description: Suggest an idea for this project
title: "[Proposal]: "
labels: ["Kind/Enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: What is the use case in which this feature is relevant?
      placeholder: A clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution
      description: Describe the solution and how it might work.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative methods
      description: Describe alternatives you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct which can be found in `CODE_OF_CONDUCT.md` file in the root of the project.
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true

